URL: https://www.dndbeyond.com/spells/{search}
SPACE: -
var result = "";
Start();
FindSection("class=\"page-heading\"");
FindSection("class=\"page-title\"");
result = result + "<color=yellow>"+GetBetween(">","<")+"<color=grey>\r\n";
Start();
FindSection("class=\"ddb-statblock-item ddb-statblock-item-school\"");
FindSection("class=\"ddb-statblock-item-value\"");
result = result + "School: "+GetBetween(">","</div")+"\r\n";
Start();
FindSection("class=\"ddb-statblock-item ddb-statblock-item-level\"");
FindSection("class=\"ddb-statblock-item-value\"");
result = result + "Level: "+GetBetween(">","</div")+"\r\n";
Start();
FindSection("class=\"ddb-statblock-item ddb-statblock-item-casting-time\"");
FindSection("class=\"ddb-statblock-item-value\"");
result = result + "Casting Time: "+GetBetween(">","</div")+"\r\n";
Start();
FindSection("class=\"ddb-statblock-item ddb-statblock-item-range-area\"");
FindSection("class=\"ddb-statblock-item-value\"");
result = result + "Range: "+GetBetween(">","</div")+"\r\n";
Start();
FindSection("class=\"ddb-statblock-item ddb-statblock-item-components\"");
FindSection("class=\"ddb-statblock-item-value\"");
result = result + "Components: "+GetBetween(">","</div")+"\r\n";
Start();
FindSection("class=\"ddb-statblock-item ddb-statblock-item-attack-save\"");
FindSection("class=\"ddb-statblock-item-value\"");
result = result + "Save: "+GetBetween(">","</div")+"\r\n";
Start();
FindSection("class=\"ddb-statblock-item ddb-statblock-item-damage-effect\"");
FindSection("class=\"ddb-statblock-item-value\"");
result = result + "Effect: "+GetBetween(">","</div")+"\r\n";
Start();
FindSection("class=\"more-info-content\"");
result = result + "Description:\r\n"+GetBetween(">","</div")+"\r\n";
return result;
